import React, { useState } from 'react';
import { UserProfile, SkillGap, AssessmentResult } from '../types';
import {
  TrendingUp,
  Award,
  AlertTriangle,
  CheckCircle2,
  BarChart3,
  PieChart,
  ShieldCheck,
  Target,
  Sparkles,
  Download,
  Calendar,
  Layers,
  ArrowUpRight,
  Flame,
  Zap,
  Info
} from 'lucide-react';

interface ProgressTrackerProps {
  user: UserProfile;
  skillGaps: SkillGap[];
  latestAssessment: AssessmentResult | null;
  setActiveTab: (tab: string) => void;
}

export const ProgressTracker: React.FC<ProgressTrackerProps> = ({
  user,
  skillGaps,
  latestAssessment,
  setActiveTab,
}) => {
  const [activeView, setActiveView] = useState<'overview' | 'skills' | 'history'>('overview');
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  // Skill category scores
  const aptitudeScore = latestAssessment?.aptitudeScore ?? 78;
  const codingScore = latestAssessment?.codingScore ?? 68;
  const commScore = latestAssessment?.communicationScore ?? 84;
  const overallReadiness = user.overallReadiness ?? 74;

  // Realistic mock history scores
  const historyData = [
    { date: 'Sep 10', readiness: 58, aptitude: 62, coding: 52, comm: 70 },
    { date: 'Sep 14', readiness: 64, aptitude: 68, coding: 58, comm: 75 },
    { date: 'Sep 18', readiness: 69, aptitude: 72, coding: 64, comm: 79 },
    { date: 'Sep 22', readiness: 71, aptitude: 75, coding: 66, comm: 82 },
    { date: 'Sep 26', readiness: overallReadiness, aptitude: aptitudeScore, coding: codingScore, comm: commScore },
  ];

  // Benchmarks comparison
  const benchmarks = [
    { category: 'Quantitative Aptitude', current: aptitudeScore, collegeAvg: 62, topTierTarget: 85 },
    { category: 'Data Structures & Coding', current: codingScore, collegeAvg: 54, topTierTarget: 88 },
    { category: 'Technical Communication', current: commScore, collegeAvg: 68, topTierTarget: 82 },
    { category: 'System Fundamentals', current: 72, collegeAvg: 58, topTierTarget: 80 },
  ];

  const handleDownloadReport = () => {
    const reportText = `
========================================
PLACEMENTPILOT AI - STUDENT READINESS REPORT
========================================
Student Name: ${user.name}
Email: ${user.email}
Target Role: ${user.targetRole}
Target Tier: ${user.targetCompanyTier}
Date: ${new Date().toLocaleDateString()}

OVERALL READINESS SCORE: ${overallReadiness}%
Learning Streak: ${user.streakDays} Days
Earned XP: ${user.totalXp} XP

SECTION SCORES:
- Aptitude & Quant: ${aptitudeScore}%
- Coding Fundamentals: ${codingScore}%
- Communication & STAR: ${commScore}%

IDENTIFIED SKILL GAPS:
${skillGaps.map((g, i) => `${i + 1}. [${g.category.toUpperCase()}] ${g.skill} (${g.gapLevel.toUpperCase()} PRIORITY) - Target: ${g.targetScore}%`).join('\n')}

GENERATED BY PLACEMENTPILOT AI - CAMPUS PLACEMENT ENGINE
========================================
    `;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PlacementPilot_Report_${user.name.replace(/\s+/g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-[#0d1224] via-[#16123d] to-[#12193b] border border-cyan-500/20 p-6 sm:p-8 shadow-xl shadow-cyan-950/20">
        <div className="absolute top-0 right-0 w-80 h-80 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-1/4 w-72 h-72 bg-purple-600/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-400/30 text-cyan-300 text-xs font-semibold mb-3">
              <TrendingUp className="w-3.5 h-3.5 text-cyan-400" />
              <span>Real-Time Diagnostic Analytics</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight flex items-center gap-3">
              Placement Progress & Skill Radar
            </h1>
            <p className="text-slate-300 text-sm mt-1.5 max-w-2xl leading-relaxed">
              Track your trajectory across core competencies, compare against {user.targetCompanyTier} benchmarks, and address weak spots before recruitment drives.
            </p>
          </div>

          <div className="flex items-center gap-3 shrink-0">
            <button
              onClick={handleDownloadReport}
              className="px-4 py-3 rounded-xl bg-slate-900/90 hover:bg-slate-800 border border-slate-700 text-slate-200 font-semibold text-xs transition-all flex items-center gap-2 shadow-sm"
            >
              <Download className="w-4 h-4 text-cyan-400" />
              <span>{downloadSuccess ? 'Downloaded!' : 'Export Report'}</span>
            </button>

            <button
              onClick={() => setActiveTab('assessment')}
              className="px-4 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-bold text-xs transition-all shadow-lg shadow-cyan-500/25 flex items-center gap-2"
            >
              <Target className="w-4 h-4 text-slate-950" />
              <span>Retake Diagnostic</span>
            </button>
          </div>
        </div>

        {/* Navigation Tabs */}
        <div className="relative z-10 mt-6 pt-5 border-t border-slate-800/80 flex items-center gap-2">
          <button
            onClick={() => setActiveView('overview')}
            className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeView === 'overview'
                ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-400/40 shadow-sm shadow-cyan-500/20'
                : 'bg-slate-900/60 text-slate-400 hover:text-slate-200 border border-slate-800'
            }`}
          >
            Overview & Benchmarks
          </button>
          <button
            onClick={() => setActiveView('skills')}
            className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeView === 'skills'
                ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-400/40 shadow-sm shadow-cyan-500/20'
                : 'bg-slate-900/60 text-slate-400 hover:text-slate-200 border border-slate-800'
            }`}
          >
            Gap Analysis ({skillGaps.length})
          </button>
          <button
            onClick={() => setActiveView('history')}
            className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
              activeView === 'history'
                ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-400/40 shadow-sm shadow-cyan-500/20'
                : 'bg-slate-900/60 text-slate-400 hover:text-slate-200 border border-slate-800'
            }`}
          >
            Score Trajectory
          </button>
        </div>
      </div>

      {/* View 1: Overview & Benchmarks */}
      {activeView === 'overview' && (
        <div className="space-y-6">
          {/* 4 Stat Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-[#0b1021]/80 border border-cyan-500/20 rounded-2xl p-5 relative overflow-hidden backdrop-blur-md">
              <div className="flex items-center justify-between text-slate-400 text-xs font-medium uppercase tracking-wider mb-2">
                <span>Placement Readiness</span>
                <Sparkles className="w-4 h-4 text-cyan-400" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-black text-cyan-300">{overallReadiness}%</span>
                <span className="text-xs text-emerald-400 font-bold">+6% this week</span>
              </div>
              <div className="w-full bg-slate-800 h-2 rounded-full mt-3 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-cyan-500 to-blue-500 h-full rounded-full transition-all duration-700"
                  style={{ width: `${overallReadiness}%` }}
                />
              </div>
              <div className="text-[11px] text-slate-400 mt-2 flex items-center justify-between">
                <span>Current Tier Target: 85%</span>
                <span className="text-cyan-400 font-semibold">{user.targetCompanyTier}</span>
              </div>
            </div>

            <div className="bg-[#0b1021]/80 border border-purple-500/20 rounded-2xl p-5 relative overflow-hidden backdrop-blur-md">
              <div className="flex items-center justify-between text-slate-400 text-xs font-medium uppercase tracking-wider mb-2">
                <span>DSA & Coding</span>
                <Zap className="w-4 h-4 text-purple-400" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-black text-purple-300">{codingScore}%</span>
                <span className="text-xs text-slate-400">Target 88%</span>
              </div>
              <div className="w-full bg-slate-800 h-2 rounded-full mt-3 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-purple-500 to-indigo-500 h-full rounded-full transition-all duration-700"
                  style={{ width: `${codingScore}%` }}
                />
              </div>
              <div className="text-[11px] text-slate-400 mt-2 flex items-center justify-between">
                <span>Solved 18 Problems</span>
                <span className="text-purple-400 font-semibold">6 pending</span>
              </div>
            </div>

            <div className="bg-[#0b1021]/80 border border-amber-500/20 rounded-2xl p-5 relative overflow-hidden backdrop-blur-md">
              <div className="flex items-center justify-between text-slate-400 text-xs font-medium uppercase tracking-wider mb-2">
                <span>Quantitative Aptitude</span>
                <Flame className="w-4 h-4 text-amber-400" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-black text-amber-300">{aptitudeScore}%</span>
                <span className="text-xs text-emerald-400 font-bold">Above avg</span>
              </div>
              <div className="w-full bg-slate-800 h-2 rounded-full mt-3 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-amber-500 to-orange-500 h-full rounded-full transition-all duration-700"
                  style={{ width: `${aptitudeScore}%` }}
                />
              </div>
              <div className="text-[11px] text-slate-400 mt-2 flex items-center justify-between">
                <span>Speed: 52s/question</span>
                <span className="text-amber-400 font-semibold">Fast</span>
              </div>
            </div>

            <div className="bg-[#0b1021]/80 border border-emerald-500/20 rounded-2xl p-5 relative overflow-hidden backdrop-blur-md">
              <div className="flex items-center justify-between text-slate-400 text-xs font-medium uppercase tracking-wider mb-2">
                <span>Communication & STAR</span>
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-black text-emerald-300">{commScore}%</span>
                <span className="text-xs text-emerald-400 font-bold">Interview Ready</span>
              </div>
              <div className="w-full bg-slate-800 h-2 rounded-full mt-3 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-emerald-500 to-teal-500 h-full rounded-full transition-all duration-700"
                  style={{ width: `${commScore}%` }}
                />
              </div>
              <div className="text-[11px] text-slate-400 mt-2 flex items-center justify-between">
                <span>4 Mocks Conducted</span>
                <span className="text-emerald-400 font-semibold">Strong</span>
              </div>
            </div>
          </div>

          {/* Benchmark Comparison Table / Visual Bars */}
          <div className="bg-[#0c1024]/90 border border-slate-800 rounded-2xl p-6 relative">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-800">
              <div>
                <h3 className="text-base font-bold text-white flex items-center gap-2">
                  <BarChart3 className="w-4 h-4 text-cyan-400" />
                  <span>Cohort Benchmark Comparison</span>
                </h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Your current scores vs. College Batch Average vs. Top Tier 1 Offers standard.
                </p>
              </div>
              <div className="flex items-center gap-4 text-xs">
                <div className="flex items-center gap-1.5">
                  <span className="w-3 h-3 rounded-full bg-cyan-400 inline-block" />
                  <span className="text-slate-300">Your Score</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <span className="w-3 h-3 rounded-full bg-slate-600 inline-block" />
                  <span className="text-slate-400">Batch Avg</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <span className="w-3 h-3 rounded-full bg-purple-500 inline-block" />
                  <span className="text-purple-300">Target Standard</span>
                </div>
              </div>
            </div>

            <div className="mt-6 space-y-6">
              {benchmarks.map((item, idx) => (
                <div key={idx} className="space-y-2">
                  <div className="flex items-center justify-between text-xs font-semibold">
                    <span className="text-slate-200">{item.category}</span>
                    <div className="flex items-center gap-4">
                      <span className="text-cyan-300 font-bold">{item.current}%</span>
                      <span className="text-slate-400 text-[11px]">Avg: {item.collegeAvg}%</span>
                      <span className="text-purple-400 text-[11px]">Target: {item.topTierTarget}%</span>
                    </div>
                  </div>

                  <div className="relative w-full h-4 bg-slate-900 rounded-lg overflow-hidden border border-slate-800">
                    {/* College Avg Marker */}
                    <div
                      className="absolute top-0 bottom-0 w-0.5 bg-slate-500 z-10"
                      style={{ left: `${item.collegeAvg}%` }}
                      title={`Batch Average: ${item.collegeAvg}%`}
                    />
                    {/* Target Marker */}
                    <div
                      className="absolute top-0 bottom-0 w-1 bg-purple-500 z-10"
                      style={{ left: `${item.topTierTarget}%` }}
                      title={`Target: ${item.topTierTarget}%`}
                    />
                    {/* User bar */}
                    <div
                      className="h-full bg-gradient-to-r from-cyan-500 to-blue-500 rounded-lg transition-all duration-700"
                      style={{ width: `${item.current}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* View 2: Detailed Gap Analysis */}
      {activeView === 'skills' && (
        <div className="space-y-4">
          <div className="bg-[#0c1024]/90 border border-slate-800 rounded-2xl p-6">
            <h3 className="text-base font-bold text-white mb-1 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-400" />
              <span>Prioritized Skill Gaps & Action Items</span>
            </h3>
            <p className="text-xs text-slate-400 mb-6">
              These topics represent your highest leverage improvement areas to boost placement offers for {user.targetRole}.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {skillGaps.map((gap, idx) => (
                <div
                  key={idx}
                  className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 hover:border-cyan-500/40 transition-all space-y-3"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <span
                          className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded ${
                            gap.gapLevel === 'High'
                              ? 'bg-rose-500/20 text-rose-300 border border-rose-500/30'
                              : gap.gapLevel === 'Medium'
                              ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                              : 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/30'
                          }`}
                        >
                          {gap.gapLevel} Priority
                        </span>
                        <span className="text-[10px] text-slate-400 uppercase font-semibold">{gap.category}</span>
                      </div>
                      <h4 className="text-sm font-bold text-white">{gap.skill}</h4>
                    </div>

                    <div className="text-right">
                      <div className="text-xs text-slate-400">Score vs Target</div>
                      <div className="text-sm font-black text-rose-400">
                        {gap.currentScore}% <span className="text-slate-400 text-xs font-normal">/ {gap.targetScore}%</span>
                      </div>
                    </div>
                  </div>

                  <p className="text-xs text-slate-300 leading-relaxed bg-[#070b18] p-3 rounded-lg border border-slate-800/80">
                    💡 <strong>Action Recommendation:</strong> {gap.priorityAction}
                  </p>

                  <div className="flex items-center justify-between pt-1">
                    <button
                      onClick={() => setActiveTab(gap.category === 'Coding Fundamentals' ? 'coding' : gap.category === 'Aptitude' ? 'learning-hub' : 'interview')}
                      className="text-xs font-bold text-cyan-400 hover:text-cyan-300 flex items-center gap-1.5 transition-colors"
                    >
                      <span>Practice Topic Now</span>
                      <ArrowUpRight className="w-3.5 h-3.5" />
                    </button>
                    <span className="text-[11px] text-slate-400 font-medium">Estimated: 45 mins</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* View 3: Score Trajectory & Historical Progression */}
      {activeView === 'history' && (
        <div className="bg-[#0c1024]/90 border border-slate-800 rounded-2xl p-6 space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <Calendar className="w-4 h-4 text-cyan-400" />
                <span>Historical Assessment Progression</span>
              </h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Tracking your trajectory over consecutive diagnostic rounds.
              </p>
            </div>
            <div className="text-xs font-bold text-emerald-400 bg-emerald-500/10 px-3 py-1 rounded-lg border border-emerald-500/20">
              Overall +16% Growth across 16 days
            </div>
          </div>

          {/* Timeline Chart Representation */}
          <div className="grid grid-cols-1 sm:grid-cols-5 gap-3">
            {historyData.map((entry, idx) => (
              <div
                key={idx}
                className="p-4 rounded-xl bg-slate-900/70 border border-slate-800 text-center space-y-2 hover:border-cyan-500/30 transition-all"
              >
                <div className="text-xs font-bold text-slate-400">{entry.date}</div>
                <div className="text-2xl font-black text-cyan-300">{entry.readiness}%</div>
                <div className="text-[10px] text-slate-400 space-y-0.5 pt-2 border-t border-slate-800">
                  <div>Coding: <span className="text-purple-300 font-semibold">{entry.coding}%</span></div>
                  <div>Aptitude: <span className="text-amber-300 font-semibold">{entry.aptitude}%</span></div>
                  <div>Comm: <span className="text-emerald-300 font-semibold">{entry.comm}%</span></div>
                </div>
              </div>
            ))}
          </div>

          <div className="p-4 rounded-xl bg-[#080d1e] border border-cyan-500/20 flex items-start gap-3 text-xs text-slate-300 leading-relaxed">
            <Info className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-cyan-300">Continuous Evaluation:</strong> Every coding test, topic quiz, and mock interview automatically updates your live readiness score and refines your daily priorities in the Daily Planner.
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
